name: bad-dependency

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  
  dependent:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: something

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo How did you get here?
