name: half working

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  
  stuck:
    runs-on: ubuntu-latest
    needs: something

    steps:
      - name: Run a one-line script
        run: echo How did you get here?

  first:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo first

  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo second
